pipeline:
  name: harness_argo_pipeline
  identifier: harness_argo_pipeline
  projectIdentifier: Hello_World
  orgIdentifier: IDP
  tags: {}
  stages:
    - stage:
        name: Prepare Gitops Repo for Dev
        identifier: Deploy_to_Dev
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          gitOpsEnabled: true
          service:
            serviceRef: harness_argo_service
          execution:
            steps:
              - step:
                  type: GitOpsUpdateReleaseRepo
                  name: Update target version of helm
                  identifier: GitOpsUpdateReleaseRepo_1
                  spec:
                    variables:
                      - name: spec.source.targetRevision
                        type: String
                        value: <+input>
                    prTitle: sample harneess PR
                  timeout: 10m
              - step:
                  type: MergePR
                  name: Merge Changes to Main
                  identifier: mergePR
                  spec:
                    deleteSourceBranch: true
                    variables: []
                  timeout: 10m
              - step:
                  type: GitOpsSync
                  name: Sync Dev Env Repo
                  identifier: Sync_Dev_Env
                  spec:
                    prune: false
                    dryRun: false
                    applyOnly: false
                    forceApply: true
                    retryStrategy: {}
                    retry: false
                    syncOptions:
                      skipSchemaValidation: false
                      autoCreateNamespace: false
                      pruneResourcesAtLast: false
                      applyOutOfSyncOnly: false
                      replaceResources: false
                      prunePropagationPolicy: background
                    applicationsList:
                      - applicationName: dev-applications
                        agentId: harnesspocargocd
                    waitTillHealthy: true
                  timeout: 10m
            rollbackSteps: []
          environment:
            environmentRef: Development
            deployToAll: false
            gitOpsClusters:
              - identifier: local_minikube
                agentIdentifier: harnesspocargocd
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
        delegateSelectors:
          - helm-delegate
        when:
          pipelineStatus: All
        gitOpsEnabled: true
    - stage:
        name: Deploy App in Dev
        identifier: Sync_Hello_App
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          gitOpsEnabled: true
          service:
            serviceRef: harness_argo_service
          execution:
            steps:
              - step:
                  type: GitOpsSync
                  name: Sync Hello App
                  identifier: Sync_Hello_App
                  spec:
                    prune: false
                    dryRun: false
                    applyOnly: false
                    forceApply: true
                    applicationsList:
                      - applicationName: hello
                        agentId: harnesspocargocd
                    retryStrategy: {}
                    retry: false
                    syncOptions:
                      skipSchemaValidation: false
                      autoCreateNamespace: false
                      pruneResourcesAtLast: false
                      applyOutOfSyncOnly: false
                      replaceResources: false
                      prunePropagationPolicy: foreground
                  timeout: 10m
            rollbackSteps: []
          environment:
            environmentRef: Development
            deployToAll: false
            gitOpsClusters:
              - identifier: local_minikube
                agentIdentifier: harnesspocargocd
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
        gitOpsEnabled: true
  properties:
    ci:
      codebase:
        connectorRef: githubconnector
        repoName: harness-argo-poc
        build: <+input>
        sparseCheckout: []
