pipeline:
  name: harness_argo_pipeline
  identifier: harness_argo_pipeline
  projectIdentifier: Hello_World
  orgIdentifier: IDP
  tags: {}
  stages:
    - stage:
        name: Deploy to Dev
        identifier: Deploy_to_Dev
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          gitOpsEnabled: true
          service:
            serviceRef: harness_argo_service
          execution:
            steps:
              - step:
                  type: GitOpsUpdateReleaseRepo
                  name: GitOpsUpdateReleaseRepo_1
                  identifier: GitOpsUpdateReleaseRepo_1
                  spec:
                    variables:
                      - name: spec.source.targetRevision
                        type: String
                        value: <+input>
                    prTitle: sample harneess PR
                  timeout: 10m
              - step:
                  type: MergePR
                  name: Merge PR
                  identifier: mergePR
                  spec:
                    deleteSourceBranch: true
                  timeout: 10m
              - step:
                  type: GitOpsFetchLinkedApps
                  name: Fetch Linked Apps
                  identifier: fetchLinkedApps
                  timeout: 10m
                  spec: {}
              - step:
                  type: GitOpsSync
                  name: GitOpsSync_1
                  identifier: GitOpsSync_1
                  spec:
                    prune: false
                    dryRun: false
                    applyOnly: false
                    forceApply: true
                    applicationsList:
                      - applicationName: dev-applications
                        agentId: harnesspocargocd
                      - applicationName: hello
                        agentId: harnesspocargocd
                    retryStrategy: {}
                    retry: false
                    syncOptions:
                      skipSchemaValidation: false
                      autoCreateNamespace: false
                      pruneResourcesAtLast: false
                      applyOutOfSyncOnly: false
                      replaceResources: false
                      prunePropagationPolicy: foreground
                    waitTillHealthy: true
                  timeout: 10m
              - step:
                  type: GitOpsSync
                  name: GitOpsSync_2
                  identifier: GitOpsSync_2
                  spec:
                    prune: false
                    dryRun: false
                    applyOnly: false
                    forceApply: true
                    applicationsList:
                      - applicationName: hello
                        agentId: harnesspocargocd
                    retryStrategy: {}
                    retry: false
                    syncOptions:
                      skipSchemaValidation: false
                      autoCreateNamespace: false
                      pruneResourcesAtLast: false
                      applyOutOfSyncOnly: false
                      replaceResources: false
                      prunePropagationPolicy: foreground
                    waitTillHealthy: true
                  timeout: 10m
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: echo "Pipeline End!"
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
            rollbackSteps: []
          environment:
            environmentRef: Development
            deployToAll: false
            gitOpsClusters:
              - identifier: local_minikube
                agentIdentifier: harnesspocargocd
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
        delegateSelectors:
          - helm-delegate
        when:
          pipelineStatus: All
  properties:
    ci:
      codebase:
        connectorRef: githubconnector
        repoName: harness-argo-poc
        build: <+input>
        sparseCheckout: []
