pipeline:
  name: harness_argo_pipeline
  identifier: harness_argo_pipeline
  projectIdentifier: Hello_World
  orgIdentifier: IDP
  tags: {}
  stages:
    - stage:
        name: Deploy to Dev
        identifier: Deploy_to_Dev
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          gitOpsEnabled: true
          service:
            serviceRef: harness_argo_service
          execution:
            steps:
              - step:
                  type: GitOpsUpdateReleaseRepo
                  name: Update Release Repo
                  identifier: updateReleaseRepo
                  timeout: 10m
                  spec: {}
              - step:
                  type: MergePR
                  name: Merge PR
                  identifier: mergePR
                  spec:
                    deleteSourceBranch: true
                  timeout: 10m
              - step:
                  type: GitOpsFetchLinkedApps
                  name: Fetch Linked Apps
                  identifier: fetchLinkedApps
                  timeout: 10m
                  spec: {}
            rollbackSteps: []
          environment:
            environmentRef: poc_dev_env
            deployToAll: false
            gitOpsClusters:
              - identifier: local_minikube
                agentIdentifier: harnesspocargocd
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
        delegateSelectors:
          - helm-delegate
        when:
          pipelineStatus: All
  properties:
    ci:
      codebase:
        connectorRef: githubconnector
        repoName: harness-argo-poc
        build: <+input>
        sparseCheckout: []
